name: mvn_test

on:
 push:


jobs:
  build_and_test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: run main
      run: |
       mvn compile
       mvn exec:java -Dexec.mainClass="com.abccompany.app.App"  

